import assert from 'node:assert/strict'
import { test } from 'node:test'
import { mkdir, mkdtemp, readFile, realpath, rm, symlink, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { directionId } from '../../dist/cleanup/direction-id.js'
import { loadDirectionManifest, openDirectionManifest, registerManagedArtifact } from '../../dist/cleanup/manifest.js'

const makeDirection = (projectId: string) => ({ projectId, branchId: 'branch', claim: { id: 'claim', version: 1 }, hypothesis: { id: 'hypothesis', version: 1 }, protocolHash: 'protocol' })

async function workspace(fn: (runDir: string) => Promise<void>) {
  const runDir = await mkdtemp(join(tmpdir(), 'ar-direction-manifest-'))
  try { await fn(runDir) } finally { await rm(runDir, { recursive: true, force: true }) }
}

test('direction manifest records exact generated bytes and is idempotent', async () => workspace(async runDir => {
  const direction = makeDirection(await realpath(runDir))
  const manifest = await openDirectionManifest(runDir, direction)
  const path = join(runDir, 'work', 'result.json')
  await mkdir(join(runDir, 'work'), { recursive: true })
  await writeFile(path, '{"ok":true}')
  const first = await registerManagedArtifact(runDir, manifest.id, { relativePath: 'work/result.json', kind: 'result', producer: 'worker' })
  const second = await registerManagedArtifact(runDir, manifest.id, { relativePath: 'work/result.json', kind: 'result', producer: 'worker' })
  assert.deepEqual(second, first)
  const loaded = await loadDirectionManifest(runDir, directionId(direction))
  assert.equal(loaded.artifacts.length, 1)
  assert.equal(loaded.artifacts[0]?.hash, first.hash)
  assert.equal(JSON.parse(await readFile(join(runDir, '.autoresearch', 'directions', `${manifest.id}.json`), 'utf8')).contentHash, loaded.contentHash)
}))

test('direction manifest rejects symlink artifacts and changed ownership bytes', async () => workspace(async runDir => {
  const direction = makeDirection(await realpath(runDir))
  const manifest = await openDirectionManifest(runDir, direction)
  const outside = await mkdtemp(join(tmpdir(), 'ar-direction-manifest-outside-'))
  try {
    await writeFile(join(outside, 'secret.txt'), 'secret')
    await symlink(join(outside, 'secret.txt'), join(runDir, 'link.txt'))
    await assert.rejects(() => registerManagedArtifact(runDir, manifest.id, { relativePath: 'link.txt', kind: 'result', producer: 'worker' }), /escapes|regular|symlink/i)
    await mkdir(join(runDir, 'work'), { recursive: true })
    await writeFile(join(runDir, 'work.txt'), 'first')
    await registerManagedArtifact(runDir, manifest.id, { relativePath: 'work.txt', kind: 'result', producer: 'worker' })
    await writeFile(join(runDir, 'work.txt'), 'second')
    await assert.rejects(() => registerManagedArtifact(runDir, manifest.id, { relativePath: 'work.txt', kind: 'result', producer: 'worker' }), /conflict|ownership/i)
  } finally { await rm(outside, { recursive: true, force: true }) }
}))
