export const STATE_FILE = 'state.json'
export const EVENTS_FILE = 'events.jsonl'
export const RESEARCH_TREE_FILE = 'research_tree.json'
export const EVIDENCE_CHAIN_FILE = 'evidence_chain.json'
export const RUBRIC_FILE = 'RUBRIC.md'
export const PLAN_PREFIX = 'PLAN-v'
export const DECISION_FILE = 'DECISION.md'
export const PAPER_DRAFT_FILE = 'paper_draft.md'
export const FINAL_REPORT_FILE = 'FINAL_REPORT.md'
export const FAILURE_REPORT_FILE = 'FAILURE_REPORT.md'
export const WORK_DIR = 'work'
export const INPUT_DIR = 'input'
export const CANDIDATE_FILE = 'candidate.md'
export const PROFILE_FILE = 'PROFILE.md'

export const DEFAULT_MAX_CYCLES = 5
export const DEFAULT_SUBAGENT_PROVIDER = 'spawn'
